"""add_organization_unit_type_model

Revision ID: 046c21c81dff
Revises: 3a0b81ef31b6
Create Date: 2026-07-18 14:16:28.909887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046c21c81dff'
down_revision = '678f8de2055a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
