"""add_veterinary_functional_domain_model

Revision ID: 04d3bec3ba70
Revises: e1ac3fd526bf
Create Date: 2026-07-18 14:18:09.506079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d3bec3ba70'
down_revision = 'e1ac3fd526bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
