"""add_organization_unit_contact_model

Revision ID: 05ebeeaa3c2a
Revises: 143272ae4618
Create Date: 2026-07-18 14:20:18.788046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ebeeaa3c2a'
down_revision = '143272ae4618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
