"""add_organization_position_model

Revision ID: 075ffb51974c
Revises: 816403cd56f7
Create Date: 2026-07-18 14:19:38.440685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075ffb51974c'
down_revision = '816403cd56f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
