"""add gis vaccine distribution

Revision ID: 0e31bcd9ce7d
Revises: 9139e94cb178
Create Date: 2026-08-04 13:54:55.693141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e31bcd9ce7d'
down_revision = '9139e94cb178'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_vaccine_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distribution_vaccine_center_vcode', sa.String(), nullable=True),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=True),
    sa.Column('province_name', sa.String(), nullable=True),
    sa.Column('county_name', sa.String(), nullable=True),
    sa.Column('distribution_date', sa.Date(), nullable=True),
    sa.Column('distribution_status_id', sa.Integer(), nullable=True),
    sa.Column('destination_province', sa.String(), nullable=True),
    sa.Column('destination_county', sa.String(), nullable=True),
    sa.Column('destination_unit_code', sa.String(), nullable=True),
    sa.Column('destination_unit_name', sa.String(), nullable=True),
    sa.Column('destination_unit_type', sa.String(), nullable=True),
    sa.Column('vaccine_type', sa.String(), nullable=True),
    sa.Column('vaccine_brand', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('vaccine_shape', sa.String(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('dose_volume', sa.Float(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('user_code', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_vaccine_distributions_distribution_vaccine_center_vcode'), 'gis_vaccine_distributions', ['distribution_vaccine_center_vcode'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_distributions_epidemiology_unit_id'), 'gis_vaccine_distributions', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_distributions_id'), 'gis_vaccine_distributions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_vaccine_distributions_id'), table_name='gis_vaccine_distributions')
    op.drop_index(op.f('ix_gis_vaccine_distributions_epidemiology_unit_id'), table_name='gis_vaccine_distributions')
    op.drop_index(op.f('ix_gis_vaccine_distributions_distribution_vaccine_center_vcode'), table_name='gis_vaccine_distributions')
    op.drop_table('gis_vaccine_distributions')
    # ### end Alembic commands ###
