"""initial schema

Revision ID: 0e7790bf7321
Revises: 
Create Date: 2026-08-03 02:06:34.037523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7790bf7321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('geographic_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('area_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['geographic_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geographic_areas_code'), 'geographic_areas', ['code'], unique=True)
    op.create_index(op.f('ix_geographic_areas_id'), 'geographic_areas', ['id'], unique=False)
    op.create_table('gis_epidemiology_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('unit_name', sa.String(length=255), nullable=True),
    sa.Column('unit_code', sa.String(length=100), nullable=True),
    sa.Column('old_unit_code', sa.String(length=100), nullable=True),
    sa.Column('unit_type', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('x', sa.Numeric(), nullable=True),
    sa.Column('y', sa.Numeric(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_code', sa.String(length=100), nullable=True),
    sa.Column('sheep_count', sa.Integer(), nullable=True),
    sa.Column('cattle_count', sa.Integer(), nullable=True),
    sa.Column('goat_count', sa.Integer(), nullable=True),
    sa.Column('parent_unit_code', sa.String(length=100), nullable=True),
    sa.Column('registration_date', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('horse_count', sa.Integer(), nullable=True),
    sa.Column('dog_count', sa.Integer(), nullable=True),
    sa.Column('camel_count', sa.Integer(), nullable=True),
    sa.Column('buffalo_count', sa.Integer(), nullable=True),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('sanitary_license_number', sa.String(length=100), nullable=True),
    sa.Column('sanitary_license_date', sa.String(length=10), nullable=True),
    sa.Column('operation_license_number', sa.String(length=100), nullable=True),
    sa.Column('operation_license_date', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('window_code', sa.String(length=100), nullable=True),
    sa.Column('operation_license_type', sa.String(length=255), nullable=True),
    sa.Column('has_sub_unit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_epidemiology_units_unit_code'), 'gis_epidemiology_units', ['unit_code'], unique=False)
    op.create_table('inspection_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_types_id'), 'inspection_types', ['id'], unique=False)
    op.create_table('organization_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_levels_code'), 'organization_levels', ['code'], unique=True)
    op.create_index(op.f('ix_organization_levels_id'), 'organization_levels', ['id'], unique=False)
    op.create_table('organization_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('is_managerial', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_positions_code'), 'organization_positions', ['code'], unique=True)
    op.create_index(op.f('ix_organization_positions_id'), 'organization_positions', ['id'], unique=False)
    op.create_table('organization_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_managerial', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_roles_code'), 'organization_roles', ['code'], unique=True)
    op.create_index(op.f('ix_organization_roles_id'), 'organization_roles', ['id'], unique=False)
    op.create_table('organization_unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_unit_types_code'), 'organization_unit_types', ['code'], unique=True)
    op.create_index(op.f('ix_organization_unit_types_id'), 'organization_unit_types', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_province_id'), 'province', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_id'), 'user_account', ['id'], unique=False)
    op.create_index(op.f('ix_user_account_mobile'), 'user_account', ['mobile'], unique=True)
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_type_id'], ['inspection_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_id'), 'checklists', ['id'], unique=False)
    op.create_table('county',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_county_id'), 'county', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    op.create_table('organization_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('unit_type', sa.String(length=200), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['organization_levels.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['organization_unit_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_units_code'), 'organization_units', ['code'], unique=True)
    op.create_index(op.f('ix_organization_units_id'), 'organization_units', ['id'], unique=False)
    op.create_index(op.f('ix_organization_units_level_id'), 'organization_units', ['level_id'], unique=False)
    op.create_index(op.f('ix_organization_units_type_id'), 'organization_units', ['type_id'], unique=False)
    op.create_table('veterinary_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veterinary_units_code'), 'veterinary_units', ['code'], unique=True)
    op.create_index(op.f('ix_veterinary_units_id'), 'veterinary_units', ['id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_number', sa.String(length=50), nullable=False),
    sa.Column('inspection_type_id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('veterinary_unit_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspectionstatusenum'), nullable=False),
    sa.Column('result', sa.Enum('ACCEPTED', 'REJECTED', 'CONDITIONAL', 'PENDING', name='inspectionresultenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_type_id'], ['inspection_types.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['veterinary_unit_id'], ['veterinary_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_number'), 'inspections', ['inspection_number'], unique=True)
    op.create_table('organization_structure_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_structure_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_structure_nodes_id'), 'organization_structure_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_organization_structure_nodes_organization_unit_id'), 'organization_structure_nodes', ['organization_unit_id'], unique=False)
    op.create_index(op.f('ix_organization_structure_nodes_parent_id'), 'organization_structure_nodes', ['parent_id'], unique=False)
    op.create_table('organization_unit_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('geographic_area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['geographic_area_id'], ['geographic_areas.id'], ),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_unit_areas_id'), 'organization_unit_areas', ['id'], unique=False)
    op.create_table('organization_unit_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('organization_position_id', sa.Integer(), nullable=False),
    sa.Column('parent_assignment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_position_id'], ['organization_positions.id'], ),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['parent_assignment_id'], ['organization_unit_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_unit_positions_id'), 'organization_unit_positions', ['id'], unique=False)
    op.create_index(op.f('ix_organization_unit_positions_organization_position_id'), 'organization_unit_positions', ['organization_position_id'], unique=False)
    op.create_index(op.f('ix_organization_unit_positions_organization_unit_id'), 'organization_unit_positions', ['organization_unit_id'], unique=False)
    op.create_table('inspection_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_assignments_id'), 'inspection_assignments', ['id'], unique=False)
    op.create_table('inspection_item_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('inspector_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_item_results_id'), 'inspection_item_results', ['id'], unique=False)
    op.create_table('inspection_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspectionstatusenum'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspectionstatusenum'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_status_history_id'), 'inspection_status_history', ['id'], unique=False)
    op.create_table('user_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_position_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['organization_unit_position_id'], ['organization_unit_positions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_unit_id', 'organization_unit_position_id', 'is_active', name='uq_active_user_assignment_position')
    )
    op.create_index(op.f('ix_user_assignments_id'), 'user_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_assignments_id'), table_name='user_assignments')
    op.drop_table('user_assignments')
    op.drop_index(op.f('ix_inspection_status_history_id'), table_name='inspection_status_history')
    op.drop_table('inspection_status_history')
    op.drop_index(op.f('ix_inspection_item_results_id'), table_name='inspection_item_results')
    op.drop_table('inspection_item_results')
    op.drop_index(op.f('ix_inspection_assignments_id'), table_name='inspection_assignments')
    op.drop_table('inspection_assignments')
    op.drop_index(op.f('ix_organization_unit_positions_organization_unit_id'), table_name='organization_unit_positions')
    op.drop_index(op.f('ix_organization_unit_positions_organization_position_id'), table_name='organization_unit_positions')
    op.drop_index(op.f('ix_organization_unit_positions_id'), table_name='organization_unit_positions')
    op.drop_table('organization_unit_positions')
    op.drop_index(op.f('ix_organization_unit_areas_id'), table_name='organization_unit_areas')
    op.drop_table('organization_unit_areas')
    op.drop_index(op.f('ix_organization_structure_nodes_parent_id'), table_name='organization_structure_nodes')
    op.drop_index(op.f('ix_organization_structure_nodes_organization_unit_id'), table_name='organization_structure_nodes')
    op.drop_index(op.f('ix_organization_structure_nodes_id'), table_name='organization_structure_nodes')
    op.drop_table('organization_structure_nodes')
    op.drop_index(op.f('ix_inspections_inspection_number'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_veterinary_units_id'), table_name='veterinary_units')
    op.drop_index(op.f('ix_veterinary_units_code'), table_name='veterinary_units')
    op.drop_table('veterinary_units')
    op.drop_index(op.f('ix_organization_units_type_id'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_level_id'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_id'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_code'), table_name='organization_units')
    op.drop_table('organization_units')
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_county_id'), table_name='county')
    op.drop_table('county')
    op.drop_index(op.f('ix_checklists_id'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_mobile'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_province_id'), table_name='province')
    op.drop_table('province')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organization_unit_types_id'), table_name='organization_unit_types')
    op.drop_index(op.f('ix_organization_unit_types_code'), table_name='organization_unit_types')
    op.drop_table('organization_unit_types')
    op.drop_index(op.f('ix_organization_roles_id'), table_name='organization_roles')
    op.drop_index(op.f('ix_organization_roles_code'), table_name='organization_roles')
    op.drop_table('organization_roles')
    op.drop_index(op.f('ix_organization_positions_id'), table_name='organization_positions')
    op.drop_index(op.f('ix_organization_positions_code'), table_name='organization_positions')
    op.drop_table('organization_positions')
    op.drop_index(op.f('ix_organization_levels_id'), table_name='organization_levels')
    op.drop_index(op.f('ix_organization_levels_code'), table_name='organization_levels')
    op.drop_table('organization_levels')
    op.drop_index(op.f('ix_inspection_types_id'), table_name='inspection_types')
    op.drop_table('inspection_types')
    op.drop_table('inspection_areas')
    op.drop_index(op.f('ix_gis_epidemiology_units_unit_code'), table_name='gis_epidemiology_units')
    op.drop_table('gis_epidemiology_units')
    op.drop_index(op.f('ix_geographic_areas_id'), table_name='geographic_areas')
    op.drop_index(op.f('ix_geographic_areas_code'), table_name='geographic_areas')
    op.drop_table('geographic_areas')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
