"""add_organization_unit_type_model

Revision ID: 143272ae4618
Revises: 075ffb51974c
Create Date: 2026-07-18 14:19:56.106212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143272ae4618'
down_revision = '075ffb51974c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
