"""add organization unit type

Revision ID: 1b2bf9ec3892
Revises: db66b65e3bc0
Create Date: 2026-07-18 14:37:48.281864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2bf9ec3892'
down_revision = 'db66b65e3bc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_unit_types_code'), 'organization_unit_types', ['code'], unique=True)
    op.create_index(op.f('ix_organization_unit_types_id'), 'organization_unit_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_unit_types_id'), table_name='organization_unit_types')
    op.drop_index(op.f('ix_organization_unit_types_code'), table_name='organization_unit_types')
    op.drop_table('organization_unit_types')
    # ### end Alembic commands ###
