"""add gis disease report

Revision ID: 1d7ad9e04e12
Revises: d7649eace0de
Create Date: 2026-08-04 13:53:47.466620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7ad9e04e12'
down_revision = 'd7649eace0de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_disease_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_detail_vcode', sa.String(), nullable=True),
    sa.Column('observation_vcode', sa.String(), nullable=True),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('province_name', sa.String(), nullable=True),
    sa.Column('county_name', sa.String(), nullable=True),
    sa.Column('animal_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('total_animals', sa.Integer(), nullable=True),
    sa.Column('infected_count', sa.Integer(), nullable=True),
    sa.Column('dead_count', sa.Integer(), nullable=True),
    sa.Column('slaughtered_count', sa.Integer(), nullable=True),
    sa.Column('destroyed_count', sa.Integer(), nullable=True),
    sa.Column('sampling', sa.String(), nullable=True),
    sa.Column('old_information_id', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('user_code', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('operation_license_type', sa.String(), nullable=True),
    sa.Column('source_unit_code', sa.String(), nullable=True),
    sa.Column('source_unit_name', sa.String(), nullable=True),
    sa.Column('source_unit_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['gis_diseases.id'], ),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_disease_reports_disease_id'), 'gis_disease_reports', ['disease_id'], unique=False)
    op.create_index(op.f('ix_gis_disease_reports_epidemiology_unit_id'), 'gis_disease_reports', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_disease_reports_id'), 'gis_disease_reports', ['id'], unique=False)
    op.create_index(op.f('ix_gis_disease_reports_observation_detail_vcode'), 'gis_disease_reports', ['observation_detail_vcode'], unique=False)
    op.create_index(op.f('ix_gis_disease_reports_observation_vcode'), 'gis_disease_reports', ['observation_vcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_disease_reports_observation_vcode'), table_name='gis_disease_reports')
    op.drop_index(op.f('ix_gis_disease_reports_observation_detail_vcode'), table_name='gis_disease_reports')
    op.drop_index(op.f('ix_gis_disease_reports_id'), table_name='gis_disease_reports')
    op.drop_index(op.f('ix_gis_disease_reports_epidemiology_unit_id'), table_name='gis_disease_reports')
    op.drop_index(op.f('ix_gis_disease_reports_disease_id'), table_name='gis_disease_reports')
    op.drop_table('gis_disease_reports')
    # ### end Alembic commands ###
