"""add organization unit position model

Revision ID: 23301ceb373f
Revises: 7214c18c930f
Create Date: 2026-07-18 14:51:51.670972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23301ceb373f'
down_revision = '7214c18c930f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_unit_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('organization_position_id', sa.Integer(), nullable=False),
    sa.Column('parent_assignment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_position_id'], ['organization_positions.id'], ),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['parent_assignment_id'], ['organization_unit_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_unit_positions_id'), 'organization_unit_positions', ['id'], unique=False)
    op.create_index(op.f('ix_organization_unit_positions_organization_position_id'), 'organization_unit_positions', ['organization_position_id'], unique=False)
    op.create_index(op.f('ix_organization_unit_positions_organization_unit_id'), 'organization_unit_positions', ['organization_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_unit_positions_organization_unit_id'), table_name='organization_unit_positions')
    op.drop_index(op.f('ix_organization_unit_positions_organization_position_id'), table_name='organization_unit_positions')
    op.drop_index(op.f('ix_organization_unit_positions_id'), table_name='organization_unit_positions')
    op.drop_table('organization_unit_positions')
    # ### end Alembic commands ###
