"""add gis import models

Revision ID: 380cbdc3b50e
Revises: 0e7790bf7321
Create Date: 2026-08-03 09:32:54.416823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380cbdc3b50e'
down_revision = '0e7790bf7321'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_epidemiology_unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_gis_epidemiology_unit_types_id'), 'gis_epidemiology_unit_types', ['id'], unique=False)
    op.create_table('gis_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('import_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('success_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_jobs_id'), 'gis_import_jobs', ['id'], unique=False)
    op.create_table('gis_import_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_queue_id'), 'gis_import_queue', ['id'], unique=False)
    op.create_table('gis_import_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('template_code', sa.String(length=100), nullable=True),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_schedules_id'), 'gis_import_schedules', ['id'], unique=False)
    op.create_table('gis_import_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key')
    )
    op.create_index(op.f('ix_gis_import_sessions_id'), 'gis_import_sessions', ['id'], unique=False)
    op.create_table('gis_import_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=255), nullable=False),
    sa.Column('setting_value', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_index(op.f('ix_gis_import_settings_id'), 'gis_import_settings', ['id'], unique=False)
    op.create_table('gis_import_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_table', sa.String(length=100), nullable=False),
    sa.Column('worksheet_name', sa.String(length=100), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_templates_code'), 'gis_import_templates', ['code'], unique=True)
    op.create_index(op.f('ix_gis_import_templates_id'), 'gis_import_templates', ['id'], unique=False)
    op.create_table('gis_provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_code', sa.String(length=10), nullable=False),
    sa.Column('province_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_provinces_id'), 'gis_provinces', ['id'], unique=False)
    op.create_index(op.f('ix_gis_provinces_province_code'), 'gis_provinces', ['province_code'], unique=True)
    op.create_table('gis_counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('county_code', sa.String(length=10), nullable=False),
    sa.Column('county_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['gis_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_counties_county_code'), 'gis_counties', ['county_code'], unique=False)
    op.create_index(op.f('ix_gis_counties_id'), 'gis_counties', ['id'], unique=False)
    op.create_index(op.f('ix_gis_counties_province_id'), 'gis_counties', ['province_id'], unique=False)
    op.create_table('gis_import_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('excel_column', sa.String(length=255), nullable=False),
    sa.Column('database_column', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['gis_import_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_columns_id'), 'gis_import_columns', ['id'], unique=False)
    op.create_table('gis_import_duplicate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['gis_import_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_duplicate_id'), 'gis_import_duplicate', ['id'], unique=False)
    op.create_table('gis_import_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['gis_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_files_id'), 'gis_import_files', ['id'], unique=False)
    op.create_table('gis_import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['gis_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_history_id'), 'gis_import_history', ['id'], unique=False)
    op.create_table('gis_import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['gis_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_logs_id'), 'gis_import_logs', ['id'], unique=False)
    op.create_table('gis_import_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('source_field', sa.String(length=255), nullable=True),
    sa.Column('destination_field', sa.String(length=255), nullable=True),
    sa.Column('transform_rule', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['gis_import_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_mapping_id'), 'gis_import_mapping', ['id'], unique=False)
    op.create_table('gis_import_preview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('preview_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['gis_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_preview_id'), 'gis_import_preview', ['id'], unique=False)
    op.create_table('gis_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['gis_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_rows_id'), 'gis_import_rows', ['id'], unique=False)
    op.create_table('gis_import_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('imported_rows', sa.Integer(), nullable=True),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('invalid_rows', sa.Integer(), nullable=True),
    sa.Column('skipped_rows', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['gis_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_statistics_id'), 'gis_import_statistics', ['id'], unique=False)
    op.create_table('gis_import_validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('validation_type', sa.String(length=100), nullable=True),
    sa.Column('validation_value', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['gis_import_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_validation_id'), 'gis_import_validation', ['id'], unique=False)
    op.create_table('gis_import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['row_id'], ['gis_import_rows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_import_errors_id'), 'gis_import_errors', ['id'], unique=False)
    op.add_column('gis_epidemiology_units', sa.Column('old_code', sa.String(length=50), nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('unit_type_id', sa.Integer(), nullable=False))
    op.add_column('gis_epidemiology_units', sa.Column('province_id', sa.Integer(), nullable=False))
    op.add_column('gis_epidemiology_units', sa.Column('county_id', sa.Integer(), nullable=False))
    op.add_column('gis_epidemiology_units', sa.Column('parent_unit_id', sa.Integer(), nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('license_no', sa.String(length=100), nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('license_date', sa.Date(), nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('business_license_no', sa.String(length=100), nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('business_license_date', sa.Date(), nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('license_type', sa.String(length=100), nullable=True))
    op.alter_column('gis_epidemiology_units', 'unit_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('gis_epidemiology_units', 'window_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('gis_epidemiology_units', 'unit_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('gis_epidemiology_units', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('gis_epidemiology_units', 'postal_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('gis_epidemiology_units', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_gis_epidemiology_units_unit_code'), table_name='gis_epidemiology_units')
    op.create_index(op.f('ix_gis_epidemiology_units_unit_code'), 'gis_epidemiology_units', ['unit_code'], unique=True)
    op.create_index(op.f('ix_gis_epidemiology_units_county_id'), 'gis_epidemiology_units', ['county_id'], unique=False)
    op.create_index(op.f('ix_gis_epidemiology_units_id'), 'gis_epidemiology_units', ['id'], unique=False)
    op.create_index(op.f('ix_gis_epidemiology_units_province_id'), 'gis_epidemiology_units', ['province_id'], unique=False)
    op.create_index(op.f('ix_gis_epidemiology_units_unit_type_id'), 'gis_epidemiology_units', ['unit_type_id'], unique=False)
    op.create_foreign_key(None, 'gis_epidemiology_units', 'gis_counties', ['county_id'], ['id'])
    op.create_foreign_key(None, 'gis_epidemiology_units', 'gis_epidemiology_unit_types', ['unit_type_id'], ['id'])
    op.create_foreign_key(None, 'gis_epidemiology_units', 'gis_epidemiology_units', ['parent_unit_id'], ['id'])
    op.create_foreign_key(None, 'gis_epidemiology_units', 'gis_provinces', ['province_id'], ['id'])
    op.drop_column('gis_epidemiology_units', 'user_code')
    op.drop_column('gis_epidemiology_units', 'y')
    op.drop_column('gis_epidemiology_units', 'registration_date')
    op.drop_column('gis_epidemiology_units', 'operation_license_date')
    op.drop_column('gis_epidemiology_units', 'horse_count')
    op.drop_column('gis_epidemiology_units', 'dog_count')
    op.drop_column('gis_epidemiology_units', 'county')
    op.drop_column('gis_epidemiology_units', 'sanitary_license_date')
    op.drop_column('gis_epidemiology_units', 'sanitary_license_number')
    op.drop_column('gis_epidemiology_units', 'operation_license_type')
    op.drop_column('gis_epidemiology_units', 'unit_type')
    op.drop_column('gis_epidemiology_units', 'x')
    op.drop_column('gis_epidemiology_units', 'row_number')
    op.drop_column('gis_epidemiology_units', 'cattle_count')
    op.drop_column('gis_epidemiology_units', 'province')
    op.drop_column('gis_epidemiology_units', 'user_name')
    op.drop_column('gis_epidemiology_units', 'parent_unit_code')
    op.drop_column('gis_epidemiology_units', 'buffalo_count')
    op.drop_column('gis_epidemiology_units', 'has_sub_unit')
    op.drop_column('gis_epidemiology_units', 'operation_license_number')
    op.drop_column('gis_epidemiology_units', 'old_unit_code')
    op.drop_column('gis_epidemiology_units', 'goat_count')
    op.drop_column('gis_epidemiology_units', 'sheep_count')
    op.drop_column('gis_epidemiology_units', 'camel_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gis_epidemiology_units', sa.Column('camel_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('sheep_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('goat_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('old_unit_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('operation_license_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('has_sub_unit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('buffalo_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('parent_unit_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('cattle_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('x', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('unit_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('operation_license_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('sanitary_license_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('sanitary_license_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('county', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('dog_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('horse_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('operation_license_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('registration_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('y', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('gis_epidemiology_units', sa.Column('user_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gis_epidemiology_units', type_='foreignkey')
    op.drop_constraint(None, 'gis_epidemiology_units', type_='foreignkey')
    op.drop_constraint(None, 'gis_epidemiology_units', type_='foreignkey')
    op.drop_constraint(None, 'gis_epidemiology_units', type_='foreignkey')
    op.drop_index(op.f('ix_gis_epidemiology_units_unit_type_id'), table_name='gis_epidemiology_units')
    op.drop_index(op.f('ix_gis_epidemiology_units_province_id'), table_name='gis_epidemiology_units')
    op.drop_index(op.f('ix_gis_epidemiology_units_id'), table_name='gis_epidemiology_units')
    op.drop_index(op.f('ix_gis_epidemiology_units_county_id'), table_name='gis_epidemiology_units')
    op.drop_index(op.f('ix_gis_epidemiology_units_unit_code'), table_name='gis_epidemiology_units')
    op.create_index(op.f('ix_gis_epidemiology_units_unit_code'), 'gis_epidemiology_units', ['unit_code'], unique=False)
    op.alter_column('gis_epidemiology_units', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('gis_epidemiology_units', 'postal_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('gis_epidemiology_units', 'address',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('gis_epidemiology_units', 'unit_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('gis_epidemiology_units', 'window_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('gis_epidemiology_units', 'unit_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('gis_epidemiology_units', 'license_type')
    op.drop_column('gis_epidemiology_units', 'business_license_date')
    op.drop_column('gis_epidemiology_units', 'business_license_no')
    op.drop_column('gis_epidemiology_units', 'license_date')
    op.drop_column('gis_epidemiology_units', 'license_no')
    op.drop_column('gis_epidemiology_units', 'longitude')
    op.drop_column('gis_epidemiology_units', 'latitude')
    op.drop_column('gis_epidemiology_units', 'parent_unit_id')
    op.drop_column('gis_epidemiology_units', 'county_id')
    op.drop_column('gis_epidemiology_units', 'province_id')
    op.drop_column('gis_epidemiology_units', 'unit_type_id')
    op.drop_column('gis_epidemiology_units', 'old_code')
    op.drop_index(op.f('ix_gis_import_errors_id'), table_name='gis_import_errors')
    op.drop_table('gis_import_errors')
    op.drop_index(op.f('ix_gis_import_validation_id'), table_name='gis_import_validation')
    op.drop_table('gis_import_validation')
    op.drop_index(op.f('ix_gis_import_statistics_id'), table_name='gis_import_statistics')
    op.drop_table('gis_import_statistics')
    op.drop_index(op.f('ix_gis_import_rows_id'), table_name='gis_import_rows')
    op.drop_table('gis_import_rows')
    op.drop_index(op.f('ix_gis_import_preview_id'), table_name='gis_import_preview')
    op.drop_table('gis_import_preview')
    op.drop_index(op.f('ix_gis_import_mapping_id'), table_name='gis_import_mapping')
    op.drop_table('gis_import_mapping')
    op.drop_index(op.f('ix_gis_import_logs_id'), table_name='gis_import_logs')
    op.drop_table('gis_import_logs')
    op.drop_index(op.f('ix_gis_import_history_id'), table_name='gis_import_history')
    op.drop_table('gis_import_history')
    op.drop_index(op.f('ix_gis_import_files_id'), table_name='gis_import_files')
    op.drop_table('gis_import_files')
    op.drop_index(op.f('ix_gis_import_duplicate_id'), table_name='gis_import_duplicate')
    op.drop_table('gis_import_duplicate')
    op.drop_index(op.f('ix_gis_import_columns_id'), table_name='gis_import_columns')
    op.drop_table('gis_import_columns')
    op.drop_index(op.f('ix_gis_counties_province_id'), table_name='gis_counties')
    op.drop_index(op.f('ix_gis_counties_id'), table_name='gis_counties')
    op.drop_index(op.f('ix_gis_counties_county_code'), table_name='gis_counties')
    op.drop_table('gis_counties')
    op.drop_index(op.f('ix_gis_provinces_province_code'), table_name='gis_provinces')
    op.drop_index(op.f('ix_gis_provinces_id'), table_name='gis_provinces')
    op.drop_table('gis_provinces')
    op.drop_index(op.f('ix_gis_import_templates_id'), table_name='gis_import_templates')
    op.drop_index(op.f('ix_gis_import_templates_code'), table_name='gis_import_templates')
    op.drop_table('gis_import_templates')
    op.drop_index(op.f('ix_gis_import_settings_id'), table_name='gis_import_settings')
    op.drop_table('gis_import_settings')
    op.drop_index(op.f('ix_gis_import_sessions_id'), table_name='gis_import_sessions')
    op.drop_table('gis_import_sessions')
    op.drop_index(op.f('ix_gis_import_schedules_id'), table_name='gis_import_schedules')
    op.drop_table('gis_import_schedules')
    op.drop_index(op.f('ix_gis_import_queue_id'), table_name='gis_import_queue')
    op.drop_table('gis_import_queue')
    op.drop_index(op.f('ix_gis_import_jobs_id'), table_name='gis_import_jobs')
    op.drop_table('gis_import_jobs')
    op.drop_index(op.f('ix_gis_epidemiology_unit_types_id'), table_name='gis_epidemiology_unit_types')
    op.drop_table('gis_epidemiology_unit_types')
    # ### end Alembic commands ###
