"""add_organization_unit_model

Revision ID: 3a0b81ef31b6
Revises: 678f8de2055a
Create Date: 2026-07-18 14:14:47.906017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0b81ef31b6'
down_revision = '678f8de2055a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
