"""add unique constraint user assignment

Revision ID: 4a9595743f3e
Revises: 0618fa280cf0
Create Date: 2026-07-19 15:02:20.717547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a9595743f3e'
down_revision = '0618fa280cf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint('uq_active_user_assignment_position', 'user_assignments', ['user_id', 'organization_unit_id', 'organization_unit_position_id', 'is_active'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_active_user_assignment_position', 'user_assignments', type_='unique')
    op.alter_column('inspection_status_history', 'new_status',
               existing_type=sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspectionstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('inspection_status_history', 'old_status',
               existing_type=sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspectionstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('inspection_assignment_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('inspection_assignment_histories_pkey'))
    )
    # ### end Alembic commands ###
