"""add_geographic_scope_model

Revision ID: 4b21661fcbf5
Revises: 04d3bec3ba70
Create Date: 2026-07-18 14:18:45.220267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b21661fcbf5'
down_revision = '04d3bec3ba70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
