"""add_organization_position_model

Revision ID: 4f3ee93e4f6d
Revises: 4b21661fcbf5
Create Date: 2026-07-18 14:19:05.566193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3ee93e4f6d'
down_revision = '4b21661fcbf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
