"""upgrade_user_assignment_organization_structure

Revision ID: 506bbf8ecded
Revises: 696cb553e505
Create Date: 2026-07-18 14:17:24.782867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506bbf8ecded'
down_revision = '696cb553e505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
