"""add organization unit type and level relations

Revision ID: 57b401a31b54
Revises: e16ecb123f08
Create Date: 2026-07-18 14:57:31.309142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b401a31b54'
down_revision = 'e16ecb123f08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_units', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('organization_units', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_organization_units_level_id'), 'organization_units', ['level_id'], unique=False)
    op.create_index(op.f('ix_organization_units_type_id'), 'organization_units', ['type_id'], unique=False)
    op.create_foreign_key(None, 'organization_units', 'organization_levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'organization_units', 'organization_unit_types', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_units', type_='foreignkey')
    op.drop_constraint(None, 'organization_units', type_='foreignkey')
    op.drop_index(op.f('ix_organization_units_type_id'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_level_id'), table_name='organization_units')
    op.drop_column('organization_units', 'level_id')
    op.drop_column('organization_units', 'type_id')
    # ### end Alembic commands ###
