"""add_organization_position_model

Revision ID: 696cb553e505
Revises: 046c21c81dff
Create Date: 2026-07-18 14:16:59.627799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696cb553e505'
down_revision = '046c21c81dff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
