"""add gis send sample detail

Revision ID: 6bf3ff8273b3
Revises: b9f9625bc76e
Create Date: 2026-08-04 13:50:40.594985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf3ff8273b3'
down_revision = 'b9f9625bc76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_send_sample_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_sample_detail_vcode', sa.String(length=100), nullable=True),
    sa.Column('send_sample_vcode', sa.String(length=100), nullable=True),
    sa.Column('province_code', sa.String(length=50), nullable=True),
    sa.Column('province_name', sa.String(length=100), nullable=True),
    sa.Column('county_code', sa.String(length=50), nullable=True),
    sa.Column('county_name', sa.String(length=100), nullable=True),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=True),
    sa.Column('epidemiology_unit_name', sa.String(length=255), nullable=True),
    sa.Column('unit_type_name', sa.String(length=100), nullable=True),
    sa.Column('disease_or_surveillance_type', sa.String(length=255), nullable=True),
    sa.Column('animal_type', sa.String(length=100), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('sampling_date', sa.Date(), nullable=True),
    sa.Column('result_status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_send_sample_details_epidemiology_unit_id'), 'gis_send_sample_details', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_send_sample_details_id'), 'gis_send_sample_details', ['id'], unique=False)
    op.create_index(op.f('ix_gis_send_sample_details_send_sample_detail_vcode'), 'gis_send_sample_details', ['send_sample_detail_vcode'], unique=True)
    op.create_index(op.f('ix_gis_send_sample_details_send_sample_vcode'), 'gis_send_sample_details', ['send_sample_vcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_send_sample_details_send_sample_vcode'), table_name='gis_send_sample_details')
    op.drop_index(op.f('ix_gis_send_sample_details_send_sample_detail_vcode'), table_name='gis_send_sample_details')
    op.drop_index(op.f('ix_gis_send_sample_details_id'), table_name='gis_send_sample_details')
    op.drop_index(op.f('ix_gis_send_sample_details_epidemiology_unit_id'), table_name='gis_send_sample_details')
    op.drop_table('gis_send_sample_details')
    # ### end Alembic commands ###
