"""add organization position model

Revision ID: 70b9e6afd0d9
Revises: 1b2bf9ec3892
Create Date: 2026-07-18 14:40:19.074791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b9e6afd0d9'
down_revision = '1b2bf9ec3892'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('is_managerial', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_positions_code'), 'organization_positions', ['code'], unique=True)
    op.create_index(op.f('ix_organization_positions_id'), 'organization_positions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_positions_id'), table_name='organization_positions')
    op.drop_index(op.f('ix_organization_positions_code'), table_name='organization_positions')
    op.drop_table('organization_positions')
    # ### end Alembic commands ###
