"""add organization role model

Revision ID: 7214c18c930f
Revises: 8df58f916ba6
Create Date: 2026-07-18 14:51:07.001138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7214c18c930f'
down_revision = '8df58f916ba6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_managerial', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_roles_code'), 'organization_roles', ['code'], unique=True)
    op.create_index(op.f('ix_organization_roles_id'), 'organization_roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_roles_id'), table_name='organization_roles')
    op.drop_index(op.f('ix_organization_roles_code'), table_name='organization_roles')
    op.drop_table('organization_roles')
    # ### end Alembic commands ###
