"""add gis spraying

Revision ID: 7531440daa83
Revises: dba066f91827
Create Date: 2026-08-04 12:38:37.450811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7531440daa83'
down_revision = 'dba066f91827'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_spraying',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spraying_no', sa.String(length=100), nullable=False),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=False),
    sa.Column('spraying_date', sa.Date(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('spraying_operation_type', sa.String(length=100), nullable=True),
    sa.Column('pesticide_type', sa.String(length=200), nullable=True),
    sa.Column('sprayed_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sprayed_animals', sa.Integer(), nullable=True),
    sa.Column('current_animals', sa.Integer(), nullable=True),
    sa.Column('province_name', sa.String(length=100), nullable=True),
    sa.Column('county_name', sa.String(length=100), nullable=True),
    sa.Column('animal_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_spraying_epidemiology_unit_id'), 'gis_spraying', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_spraying_id'), 'gis_spraying', ['id'], unique=False)
    op.create_index(op.f('ix_gis_spraying_spraying_no'), 'gis_spraying', ['spraying_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_spraying_spraying_no'), table_name='gis_spraying')
    op.drop_index(op.f('ix_gis_spraying_id'), table_name='gis_spraying')
    op.drop_index(op.f('ix_gis_spraying_epidemiology_unit_id'), table_name='gis_spraying')
    op.drop_table('gis_spraying')
    # ### end Alembic commands ###
