"""add gis_surveillance

Revision ID: 7d641e46407a
Revises: 406c4330c4b2
Create Date: 2026-08-05 20:23:00.414577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d641e46407a'
down_revision = '406c4330c4b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_vaccine_disposals_distribution_vaccine_center_vcode'), table_name='gis_vaccine_disposals')
    op.drop_index(op.f('ix_gis_vaccine_disposals_epidemiology_unit_id'), table_name='gis_vaccine_disposals')
    op.drop_index(op.f('ix_gis_vaccine_disposals_id'), table_name='gis_vaccine_disposals')
    op.drop_table('gis_vaccine_disposals')
    op.drop_index(op.f('ix_gis_vaccine_inventories_distribution_vaccine_center_vcode'), table_name='gis_vaccine_inventories')
    op.drop_index(op.f('ix_gis_vaccine_inventories_epidemiology_unit_id'), table_name='gis_vaccine_inventories')
    op.drop_index(op.f('ix_gis_vaccine_inventories_id'), table_name='gis_vaccine_inventories')
    op.drop_table('gis_vaccine_inventories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_vaccine_inventories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('distribution_vaccine_center_vcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('province_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('county_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('distribution_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('distribution_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vaccine_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vaccine_brand', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vaccine_shape', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('package_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dose_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('production_import_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], name=op.f('gis_vaccine_inventories_epidemiology_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gis_vaccine_inventories_pkey'))
    )
    op.create_index(op.f('ix_gis_vaccine_inventories_id'), 'gis_vaccine_inventories', ['id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_inventories_epidemiology_unit_id'), 'gis_vaccine_inventories', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_inventories_distribution_vaccine_center_vcode'), 'gis_vaccine_inventories', ['distribution_vaccine_center_vcode'], unique=False)
    op.create_table('gis_vaccine_disposals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('distribution_vaccine_center_vcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distribution_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('province_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('county_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distribution_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('distribution_status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('destination_province', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_county', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_unit_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_unit_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_unit_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vaccine_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vaccine_brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vaccine_shape', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('package_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dose_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('disposal_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('disposal_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('disposal_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], name=op.f('gis_vaccine_disposals_epidemiology_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gis_vaccine_disposals_pkey'))
    )
    op.create_index(op.f('ix_gis_vaccine_disposals_id'), 'gis_vaccine_disposals', ['id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_disposals_epidemiology_unit_id'), 'gis_vaccine_disposals', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_disposals_distribution_vaccine_center_vcode'), 'gis_vaccine_disposals', ['distribution_vaccine_center_vcode'], unique=False)
    # ### end Alembic commands ###
