"""add_organization_role_model

Revision ID: 816403cd56f7
Revises: 4f3ee93e4f6d
Create Date: 2026-07-18 14:19:21.137240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816403cd56f7'
down_revision = '4f3ee93e4f6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
