"""add organization level model

Revision ID: 8df58f916ba6
Revises: 70b9e6afd0d9
Create Date: 2026-07-18 14:49:07.452230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df58f916ba6'
down_revision = '70b9e6afd0d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_levels_code'), 'organization_levels', ['code'], unique=True)
    op.create_index(op.f('ix_organization_levels_id'), 'organization_levels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_levels_id'), table_name='organization_levels')
    op.drop_index(op.f('ix_organization_levels_code'), table_name='organization_levels')
    op.drop_table('organization_levels')
    # ### end Alembic commands ###
