"""add gis vaccination performance

Revision ID: 9139e94cb178
Revises: 1d7ad9e04e12
Create Date: 2026-08-04 13:54:26.259762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9139e94cb178'
down_revision = '1d7ad9e04e12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_vaccination_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_action_vaccine_vcode', sa.String(), nullable=True),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=True),
    sa.Column('province_name', sa.String(), nullable=True),
    sa.Column('county_name', sa.String(), nullable=True),
    sa.Column('vaccination_date', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('animal_type', sa.String(), nullable=True),
    sa.Column('vaccine_type', sa.String(), nullable=True),
    sa.Column('vaccine_brand', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('total_animals', sa.Integer(), nullable=True),
    sa.Column('vaccinated_animals', sa.Integer(), nullable=True),
    sa.Column('eligible_animals', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('disease_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_code', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_vaccination_performances_control_action_vaccine_vcode'), 'gis_vaccination_performances', ['control_action_vaccine_vcode'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_performances_epidemiology_unit_id'), 'gis_vaccination_performances', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_performances_id'), 'gis_vaccination_performances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_vaccination_performances_id'), table_name='gis_vaccination_performances')
    op.drop_index(op.f('ix_gis_vaccination_performances_epidemiology_unit_id'), table_name='gis_vaccination_performances')
    op.drop_index(op.f('ix_gis_vaccination_performances_control_action_vaccine_vcode'), table_name='gis_vaccination_performances')
    op.drop_table('gis_vaccination_performances')
    # ### end Alembic commands ###
