"""add role code

Revision ID: ad5e1a4c8998
Revises: 529565a4cb7d
Create Date: 2026-08-13 15:12:24.092441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad5e1a4c8998'
down_revision = '529565a4cb7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_vaccine_disposals_distribution_vaccine_center_vcode'), table_name='gis_vaccine_disposals')
    op.drop_index(op.f('ix_gis_vaccine_disposals_epidemiology_unit_id'), table_name='gis_vaccine_disposals')
    op.drop_index(op.f('ix_gis_vaccine_disposals_id'), table_name='gis_vaccine_disposals')
    op.drop_table('gis_vaccine_disposals')
    op.drop_index(op.f('ix_gis_vaccination_kpi_snapshots_county_code'), table_name='gis_vaccination_kpi_snapshots')
    op.drop_index(op.f('ix_gis_vaccination_kpi_snapshots_province_code'), table_name='gis_vaccination_kpi_snapshots')
    op.drop_index(op.f('ix_gis_vaccination_kpi_snapshots_snapshot_date'), table_name='gis_vaccination_kpi_snapshots')
    op.drop_index(op.f('ix_gis_vaccination_kpi_snapshots_unit_code'), table_name='gis_vaccination_kpi_snapshots')
    op.drop_index(op.f('ix_gis_vaccination_kpi_snapshots_vaccine_type'), table_name='gis_vaccination_kpi_snapshots')
    op.drop_table('gis_vaccination_kpi_snapshots')
    op.drop_index(op.f('ix_gis_vaccination_kpi_alerts_alert_type'), table_name='gis_vaccination_kpi_alerts')
    op.drop_index(op.f('ix_gis_vaccination_kpi_alerts_county_code'), table_name='gis_vaccination_kpi_alerts')
    op.drop_index(op.f('ix_gis_vaccination_kpi_alerts_province_code'), table_name='gis_vaccination_kpi_alerts')
    op.drop_index(op.f('ix_gis_vaccination_kpi_alerts_severity'), table_name='gis_vaccination_kpi_alerts')
    op.drop_index(op.f('ix_gis_vaccination_kpi_alerts_snapshot_date'), table_name='gis_vaccination_kpi_alerts')
    op.drop_index(op.f('ix_gis_vaccination_kpi_alerts_unit_code'), table_name='gis_vaccination_kpi_alerts')
    op.drop_index(op.f('ix_gis_vaccination_kpi_alerts_vaccine_type'), table_name='gis_vaccination_kpi_alerts')
    op.drop_table('gis_vaccination_kpi_alerts')
    op.drop_index(op.f('ix_gis_vaccine_inventories_distribution_vaccine_center_vcode'), table_name='gis_vaccine_inventories')
    op.drop_index(op.f('ix_gis_vaccine_inventories_epidemiology_unit_id'), table_name='gis_vaccine_inventories')
    op.drop_index(op.f('ix_gis_vaccine_inventories_id'), table_name='gis_vaccine_inventories')
    op.drop_table('gis_vaccine_inventories')
    op.drop_index(op.f('ix_gis_disease_reports_observation_detail_vcode'), table_name='gis_disease_reports')
    op.create_index(op.f('ix_gis_disease_reports_observation_detail_vcode'), 'gis_disease_reports', ['observation_detail_vcode'], unique=True)
    op.drop_index(op.f('ix_gis_vaccination_performances_control_action_vaccine_vcode'), table_name='gis_vaccination_performances')
    op.create_index(op.f('ix_gis_vaccination_performances_control_action_vaccine_vcode'), 'gis_vaccination_performances', ['control_action_vaccine_vcode'], unique=True)
    op.drop_column('gis_vaccination_performances', 'user_name')
    op.drop_column('gis_vaccination_performances', 'user_code')
    op.drop_index(op.f('ix_gis_vaccine_distributions_distribution_vaccine_center_vcode'), table_name='gis_vaccine_distributions')
    op.create_index(op.f('ix_gis_vaccine_distributions_distribution_vaccine_center_vcode'), 'gis_vaccine_distributions', ['distribution_vaccine_center_vcode'], unique=True)
    op.add_column(
        "roles",
        sa.Column(
            "code",
            sa.String(length=100),
            nullable=True,
        ),
    )

    # Populate existing roles.
    # Existing role names are preserved as the initial code.
    op.execute(
        """
        UPDATE roles
        SET code = COALESCE(
            NULLIF(TRIM(name), ''),
            'ROLE_' || id::text
        )
        WHERE code IS NULL
        """
    )

    # Make the column mandatory after existing rows have been populated.
    op.alter_column(
        "roles",
        "code",
        existing_type=sa.String(length=100),
        nullable=False,
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_column('roles', 'code')
    op.drop_index(op.f('ix_gis_vaccine_distributions_distribution_vaccine_center_vcode'), table_name='gis_vaccine_distributions')
    op.create_index(op.f('ix_gis_vaccine_distributions_distribution_vaccine_center_vcode'), 'gis_vaccine_distributions', ['distribution_vaccine_center_vcode'], unique=False)
    op.add_column('gis_vaccination_performances', sa.Column('user_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gis_vaccination_performances', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_gis_vaccination_performances_control_action_vaccine_vcode'), table_name='gis_vaccination_performances')
    op.create_index(op.f('ix_gis_vaccination_performances_control_action_vaccine_vcode'), 'gis_vaccination_performances', ['control_action_vaccine_vcode'], unique=False)
    op.drop_index(op.f('ix_gis_disease_reports_observation_detail_vcode'), table_name='gis_disease_reports')
    op.create_index(op.f('ix_gis_disease_reports_observation_detail_vcode'), 'gis_disease_reports', ['observation_detail_vcode'], unique=False)
    op.create_table('gis_vaccine_inventories',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('distribution_vaccine_center_vcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('province_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('county_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('distribution_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('distribution_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vaccine_type', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('vaccine_brand', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vaccine_shape', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('package_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dose_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('production_import_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], name=op.f('gis_vaccine_inventories_epidemiology_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gis_vaccine_inventories_pkey'))
    )
    op.create_index(op.f('ix_gis_vaccine_inventories_id'), 'gis_vaccine_inventories', ['id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_inventories_epidemiology_unit_id'), 'gis_vaccine_inventories', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_inventories_distribution_vaccine_center_vcode'), 'gis_vaccine_inventories', ['distribution_vaccine_center_vcode'], unique=False)
    op.create_table('gis_vaccination_kpi_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('province_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('county_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unit_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vaccine_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gis_vaccination_kpi_alerts_pkey'))
    )
    op.create_index(op.f('ix_gis_vaccination_kpi_alerts_vaccine_type'), 'gis_vaccination_kpi_alerts', ['vaccine_type'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_alerts_unit_code'), 'gis_vaccination_kpi_alerts', ['unit_code'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_alerts_snapshot_date'), 'gis_vaccination_kpi_alerts', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_alerts_severity'), 'gis_vaccination_kpi_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_alerts_province_code'), 'gis_vaccination_kpi_alerts', ['province_code'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_alerts_county_code'), 'gis_vaccination_kpi_alerts', ['county_code'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_alerts_alert_type'), 'gis_vaccination_kpi_alerts', ['alert_type'], unique=False)
    op.create_table('gis_vaccination_kpi_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('province_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('county_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unit_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vaccine_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('coverage_percent', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('eligible_animals', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('vaccinated_animals', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('remaining_animals', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('adverse_events', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('adverse_event_rate_percent', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('effectiveness_signal', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gis_vaccination_kpi_snapshots_pkey'))
    )
    op.create_index(op.f('ix_gis_vaccination_kpi_snapshots_vaccine_type'), 'gis_vaccination_kpi_snapshots', ['vaccine_type'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_snapshots_unit_code'), 'gis_vaccination_kpi_snapshots', ['unit_code'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_snapshots_snapshot_date'), 'gis_vaccination_kpi_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_snapshots_province_code'), 'gis_vaccination_kpi_snapshots', ['province_code'], unique=False)
    op.create_index(op.f('ix_gis_vaccination_kpi_snapshots_county_code'), 'gis_vaccination_kpi_snapshots', ['county_code'], unique=False)
    op.create_table('gis_vaccine_disposals',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('distribution_vaccine_center_vcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distribution_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('province_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('county_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distribution_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('distribution_status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('destination_province', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_county', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_unit_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_unit_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_unit_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vaccine_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vaccine_brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vaccine_shape', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('package_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dose_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('disposal_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('disposal_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('disposal_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('vaccine_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('epidemiology_unit_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('distribution_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], name=op.f('gis_vaccine_disposals_epidemiology_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gis_vaccine_disposals_pkey'))
    )
    op.create_index(op.f('ix_gis_vaccine_disposals_id'), 'gis_vaccine_disposals', ['id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_disposals_epidemiology_unit_id'), 'gis_vaccine_disposals', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_vaccine_disposals_distribution_vaccine_center_vcode'), 'gis_vaccine_disposals', ['distribution_vaccine_center_vcode'], unique=False)
    # ### end Alembic commands ###
