"""add role code

Revision ID: ad5e1a4c8998
Revises: 529565a4cb7d
Create Date: 2026-08-13 15:12:24.092441

The original autogenerated migration contained unrelated destructive DROP
operations and UNIQUE-index changes for GIS source tables. The live source
contains repeated external vcodes and already has the GIS tables, so those
operations are not a valid migration for this database.

This migration is intentionally limited to adding the role code field.
"""
from alembic import op


revision = "ad5e1a4c8998"
down_revision = "529565a4cb7d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE roles ADD COLUMN IF NOT EXISTS code VARCHAR(100)")
    op.execute(
        "UPDATE roles SET code = 'ROLE_' || id::text "
        "WHERE code IS NULL OR btrim(code) = ''"
    )
    op.execute("ALTER TABLE roles ALTER COLUMN code SET NOT NULL")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_roles_code ON roles (code)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_roles_code")
    op.execute("ALTER TABLE roles DROP COLUMN IF EXISTS code")
