"""add gis slaughter disposal

Revision ID: ad952ac82f35
Revises: 7531440daa83
Create Date: 2026-08-04 13:46:05.772745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad952ac82f35'
down_revision = '7531440daa83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_slaughter_disposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_action_emha_detail_vcode', sa.String(length=100), nullable=False),
    sa.Column('control_action_emha_vcode', sa.String(length=100), nullable=True),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('animal_type', sa.String(length=100), nullable=True),
    sa.Column('slaughter_date', sa.Date(), nullable=True),
    sa.Column('existing_animal_count', sa.Integer(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('slaughtered_count', sa.Integer(), nullable=True),
    sa.Column('disposed_count', sa.Integer(), nullable=True),
    sa.Column('dead_count', sa.Integer(), nullable=True),
    sa.Column('predicted_compensation_amount', sa.Float(), nullable=True),
    sa.Column('operation_license_type', sa.String(length=255), nullable=True),
    sa.Column('window_code', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['gis_diseases.id'], ),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_slaughter_disposals_control_action_emha_detail_vcode'), 'gis_slaughter_disposals', ['control_action_emha_detail_vcode'], unique=True)
    op.create_index(op.f('ix_gis_slaughter_disposals_disease_id'), 'gis_slaughter_disposals', ['disease_id'], unique=False)
    op.create_index(op.f('ix_gis_slaughter_disposals_epidemiology_unit_id'), 'gis_slaughter_disposals', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_slaughter_disposals_id'), 'gis_slaughter_disposals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_slaughter_disposals_id'), table_name='gis_slaughter_disposals')
    op.drop_index(op.f('ix_gis_slaughter_disposals_epidemiology_unit_id'), table_name='gis_slaughter_disposals')
    op.drop_index(op.f('ix_gis_slaughter_disposals_disease_id'), table_name='gis_slaughter_disposals')
    op.drop_index(op.f('ix_gis_slaughter_disposals_control_action_emha_detail_vcode'), table_name='gis_slaughter_disposals')
    op.drop_table('gis_slaughter_disposals')
    # ### end Alembic commands ###
