"""baseline_v0_3_sync

Revision ID: c362d30c9cb4
Revises: 
Create Date: 2026-07-16 00:32:06.470734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c362d30c9cb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_province_code'), 'province', ['code'], unique=True)
    op.create_index(op.f('ix_province_id'), 'province', ['id'], unique=False)
    op.create_index(op.f('ix_province_name'), 'province', ['name'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('county',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_county_code'), 'county', ['code'], unique=True)
    op.create_index(op.f('ix_county_id'), 'county', ['id'], unique=False)
    op.create_index(op.f('ix_county_name'), 'county', ['name'], unique=False)
    op.create_table('veterinary_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veterinary_unit_code'), 'veterinary_unit', ['code'], unique=True)
    op.create_index(op.f('ix_veterinary_unit_id'), 'veterinary_unit', ['id'], unique=False)
    op.create_index(op.f('ix_veterinary_unit_name'), 'veterinary_unit', ['name'], unique=False)
    op.create_index(op.f('ix_veterinary_unit_unit_type'), 'veterinary_unit', ['unit_type'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('default_veterinary_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_veterinary_unit_id'], ['veterinary_unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_id'), 'user_account', ['id'], unique=False)
    op.create_index(op.f('ix_user_account_is_active'), 'user_account', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_account_mobile'), 'user_account', ['mobile'], unique=True)
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('veterinary_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veterinary_unit_id'], ['veterinary_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'veterinary_unit_id', name='uq_user_role_unit')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_mobile'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_is_active'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_veterinary_unit_unit_type'), table_name='veterinary_unit')
    op.drop_index(op.f('ix_veterinary_unit_name'), table_name='veterinary_unit')
    op.drop_index(op.f('ix_veterinary_unit_id'), table_name='veterinary_unit')
    op.drop_index(op.f('ix_veterinary_unit_code'), table_name='veterinary_unit')
    op.drop_table('veterinary_unit')
    op.drop_index(op.f('ix_county_name'), table_name='county')
    op.drop_index(op.f('ix_county_id'), table_name='county')
    op.drop_index(op.f('ix_county_code'), table_name='county')
    op.drop_table('county')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_province_name'), table_name='province')
    op.drop_index(op.f('ix_province_id'), table_name='province')
    op.drop_index(op.f('ix_province_code'), table_name='province')
    op.drop_table('province')
    # ### end Alembic commands ###
