"""add gis enable care

Revision ID: d7649eace0de
Revises: 6bf3ff8273b3
Create Date: 2026-08-04 13:52:34.746665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7649eace0de'
down_revision = '6bf3ff8273b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_enable_cares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enable_care_detail_vcode', sa.String(length=100), nullable=True),
    sa.Column('enable_care_vcode', sa.String(length=100), nullable=True),
    sa.Column('province_code', sa.String(length=50), nullable=True),
    sa.Column('province_name', sa.String(length=100), nullable=True),
    sa.Column('county_code', sa.String(length=50), nullable=True),
    sa.Column('county_name', sa.String(length=100), nullable=True),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=True),
    sa.Column('epidemiology_unit_name', sa.String(length=255), nullable=True),
    sa.Column('unit_type_name', sa.String(length=100), nullable=True),
    sa.Column('surveillance_type', sa.String(length=255), nullable=True),
    sa.Column('animal_type', sa.String(length=100), nullable=True),
    sa.Column('care_date', sa.Date(), nullable=True),
    sa.Column('total_animals', sa.Integer(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('suspicious_count', sa.Integer(), nullable=True),
    sa.Column('old_system_id', sa.String(length=100), nullable=True),
    sa.Column('age_group', sa.String(length=100), nullable=True),
    sa.Column('old_unit_code', sa.String(length=100), nullable=True),
    sa.Column('window_code', sa.String(length=100), nullable=True),
    sa.Column('operation_license_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_enable_cares_enable_care_detail_vcode'), 'gis_enable_cares', ['enable_care_detail_vcode'], unique=True)
    op.create_index(op.f('ix_gis_enable_cares_enable_care_vcode'), 'gis_enable_cares', ['enable_care_vcode'], unique=False)
    op.create_index(op.f('ix_gis_enable_cares_epidemiology_unit_id'), 'gis_enable_cares', ['epidemiology_unit_id'], unique=False)
    op.create_index(op.f('ix_gis_enable_cares_id'), 'gis_enable_cares', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gis_enable_cares_id'), table_name='gis_enable_cares')
    op.drop_index(op.f('ix_gis_enable_cares_epidemiology_unit_id'), table_name='gis_enable_cares')
    op.drop_index(op.f('ix_gis_enable_cares_enable_care_vcode'), table_name='gis_enable_cares')
    op.drop_index(op.f('ix_gis_enable_cares_enable_care_detail_vcode'), table_name='gis_enable_cares')
    op.drop_table('gis_enable_cares')
    # ### end Alembic commands ###
