"""add_organization_structure_models

Revision ID: db66b65e3bc0
Revises: 05ebeeaa3c2a
Create Date: 2026-07-18 14:20:59.696477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db66b65e3bc0'
down_revision = '05ebeeaa3c2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
