"""add gis disease occurrences

Revision ID: dba066f91827
Revises: ca2f1bb34f0c
Create Date: 2026-08-03 14:36:19.171222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dba066f91827'
down_revision = 'ca2f1bb34f0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_code', sa.String(length=20), nullable=True),
    sa.Column('disease_name', sa.String(length=200), nullable=False),
    sa.Column('disease_group', sa.String(length=100), nullable=True),
    sa.Column('is_notifiable', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_diseases_disease_code'), 'gis_diseases', ['disease_code'], unique=True)
    op.create_index(op.f('ix_gis_diseases_id'), 'gis_diseases', ['id'], unique=False)
    op.create_table('gis_disease_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_detail_vcode', sa.String(length=100), nullable=True),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('animal_type', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('report_number', sa.String(length=100), nullable=True),
    sa.Column('exposed_count', sa.Integer(), nullable=True),
    sa.Column('animal_count', sa.Integer(), nullable=True),
    sa.Column('infected_count', sa.Integer(), nullable=True),
    sa.Column('dead_count', sa.Integer(), nullable=True),
    sa.Column('slaughtered_count', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_code', sa.String(length=50), nullable=True),
    sa.Column('window_code', sa.String(length=100), nullable=True),
    sa.Column('operation_license_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['gis_diseases.id'], ),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_disease_occurrences_id'), 'gis_disease_occurrences', ['id'], unique=False)
    op.create_index(op.f('ix_gis_disease_occurrences_observation_detail_vcode'), 'gis_disease_occurrences', ['observation_detail_vcode'], unique=True)
    op.create_table('gis_outbreaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outbreak_no', sa.String(length=100), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('epidemiology_unit_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['gis_diseases.id'], ),
    sa.ForeignKeyConstraint(['epidemiology_unit_id'], ['gis_epidemiology_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gis_outbreaks_id'), 'gis_outbreaks', ['id'], unique=False)
    op.create_index(op.f('ix_gis_outbreaks_outbreak_no'), 'gis_outbreaks', ['outbreak_no'], unique=True)
    op.alter_column('gis_import_columns', 'column_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('gis_import_columns', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gis_import_duplicate', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gis_import_errors', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gis_import_files', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('gis_import_history', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('gis_import_jobs', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gis_import_mapping', 'excel_column',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('gis_import_mapping', 'database_field',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('gis_import_rows', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gis_import_settings', 'key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('gis_import_templates', 'entity_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('gis_import_validation', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gis_import_validation', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gis_import_templates', 'entity_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gis_import_settings', 'key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gis_import_rows', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('gis_import_mapping', 'database_field',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('gis_import_mapping', 'excel_column',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('gis_import_jobs', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gis_import_history', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gis_import_files', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('gis_import_errors', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gis_import_duplicate', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gis_import_columns', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gis_import_columns', 'column_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_gis_outbreaks_outbreak_no'), table_name='gis_outbreaks')
    op.drop_index(op.f('ix_gis_outbreaks_id'), table_name='gis_outbreaks')
    op.drop_table('gis_outbreaks')
    op.drop_index(op.f('ix_gis_disease_occurrences_observation_detail_vcode'), table_name='gis_disease_occurrences')
    op.drop_index(op.f('ix_gis_disease_occurrences_id'), table_name='gis_disease_occurrences')
    op.drop_table('gis_disease_occurrences')
    op.drop_index(op.f('ix_gis_diseases_id'), table_name='gis_diseases')
    op.drop_index(op.f('ix_gis_diseases_disease_code'), table_name='gis_diseases')
    op.drop_table('gis_diseases')
    # ### end Alembic commands ###
