"""add organization structure node model

Revision ID: e16ecb123f08
Revises: 23301ceb373f
Create Date: 2026-07-18 14:52:26.620375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16ecb123f08'
down_revision = '23301ceb373f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_structure_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_structure_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_structure_nodes_id'), 'organization_structure_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_organization_structure_nodes_organization_unit_id'), 'organization_structure_nodes', ['organization_unit_id'], unique=False)
    op.create_index(op.f('ix_organization_structure_nodes_parent_id'), 'organization_structure_nodes', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_structure_nodes_parent_id'), table_name='organization_structure_nodes')
    op.drop_index(op.f('ix_organization_structure_nodes_organization_unit_id'), table_name='organization_structure_nodes')
    op.drop_index(op.f('ix_organization_structure_nodes_id'), table_name='organization_structure_nodes')
    op.drop_table('organization_structure_nodes')
    # ### end Alembic commands ###
