"""add_organization_responsibility_model

Revision ID: e1ac3fd526bf
Revises: 506bbf8ecded
Create Date: 2026-07-18 14:17:44.387201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ac3fd526bf'
down_revision = '506bbf8ecded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
