"""increase string lengths

Revision ID: e82a89808316
Revises: cbb34563f634
Create Date: 2026-07-17 11:19:19.687998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82a89808316'
down_revision = 'cbb34563f634'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('county', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('county', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_county_code'), table_name='county')
    op.drop_index(op.f('ix_county_name'), table_name='county')
    op.create_unique_constraint(None, 'county', ['code'])
    op.drop_constraint(op.f('county_province_id_fkey'), 'county', type_='foreignkey')
    op.create_foreign_key(None, 'county', 'province', ['province_id'], ['id'])
    op.alter_column('organization_units', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('organization_units', 'unit_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('province', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('province', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_province_code'), table_name='province')
    op.drop_index(op.f('ix_province_name'), table_name='province')
    op.create_unique_constraint(None, 'province', ['code'])
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('user_account', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('user_account', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('user_account', 'email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user_account', 'mobile',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_account_is_active'), table_name='user_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_account_is_active'), 'user_account', ['is_active'], unique=False)
    op.alter_column('user_account', 'mobile',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('user_account', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('user_account', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user_account', 'username',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'province', type_='unique')
    op.create_index(op.f('ix_province_name'), 'province', ['name'], unique=False)
    op.create_index(op.f('ix_province_code'), 'province', ['code'], unique=True)
    op.alter_column('province', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('province', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('organization_units', 'unit_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('organization_units', 'code',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'county', type_='foreignkey')
    op.create_foreign_key(op.f('county_province_id_fkey'), 'county', 'province', ['province_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'county', type_='unique')
    op.create_index(op.f('ix_county_name'), 'county', ['name'], unique=False)
    op.create_index(op.f('ix_county_code'), 'county', ['code'], unique=True)
    op.alter_column('county', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('county', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
