import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getToken } from "../utils/token";
import "./VaccinationKpiOverview.css";

type Vaccine = { vaccine_type: string | null; disease_name: string | null; animal_group: string | null; animal_group_name: string | null; vaccine_brand: string | null; units: number; counties: number; target_population: number; vaccinated_animals: number; remaining_animals: number; coverage_percent: number; progress_percent: number; status: string };
type County = { county_code: string | number | null; county_name: string | null; units: number; target_population: number; vaccinated_animals: number; remaining_animals: number; coverage_percent: number; progress_percent: number; status: string };
type Surveillance = { label: string; records: number; total_animals: number; positive_count: number; negative_count: number; suspicious_count: number };
type InventoryItem = { vaccine_type: string | null; vaccine_brand: string | null; manufacturer: string | null; batch_number: string | null; province_name: string | null; county_name: string | null; unit_code: string | null; unit_name: string | null; package_count: number; expiration_date: string | null; days_to_expiry: number | null };
type Booster = { severity: "OVERDUE" | "DUE_SOON"; county_code: string | number | null; county_name: string | null; unit_code: string | null; unit_name: string | null; vaccine_type: string | null; animal_group_name: string | null; last_vaccination_date: string; due_date: string; days_until_due: number; immunity_days: number };
type Overview = { summary: { units: number; counties: number; vaccine_types: number; target_population: number; vaccinated_animals: number; remaining_animals: number; coverage_percent: number; coverage_is_valid: boolean; province_names: string[] }; executive_vaccines: string[]; vaccines: Vaccine[]; counties: County[]; booster_alerts: Booster[]; booster_by_county: Array<{ county_code: string | number | null; county_name: string | null; due_soon: number; overdue: number; total_alerts: number; units: Booster[] }>; booster_alert_days: number; fmd_immunity_days: number; default_immunity_days: number; inventory_summary: { total_lots: number; total_packages: number; near_expiry_days: number; near_expiry_lots: number; near_expiry: InventoryItem[]; inventory: InventoryItem[] }; surveillance: Surveillance[]; generated_at: string };

const API_BASE = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000/api/v1";
const EXECUTIVE = ["شاربن", "تب برفکی", "آبله", "لمپی‌اسکین", "PPR", "FD REV1", "بروسلوز میش", "RD IRIBA", "FD IRIBA", "هاری"];
const COLORS = ["#22d3ee", "#38bdf8", "#60a5fa", "#34d399", "#fbbf24", "#fb7185", "#a78bfa", "#2dd4bf", "#4ade80", "#fb923c"];
const fmt = (v: number | string | null | undefined) => new Intl.NumberFormat("fa-IR").format(Number(v || 0));
const pct = (v: number | string | null | undefined) => `${Number(v || 0).toFixed(1)}%`;
const dateFa = (v: string | null | undefined) => { if (!v) return "-"; const d = new Date(v); return Number.isNaN(d.getTime()) ? v : new Intl.DateTimeFormat("fa-IR").format(d); };
const normalize = (s: string | null | undefined) => String(s || "").replace(/\u200c/g, "").toLowerCase();
const statusText = (s: string) => ({ EXCELLENT: "عالی", ON_TRACK: "در مسیر", WARNING: "نیازمند توجه", CRITICAL: "بحرانی", NO_TARGET: "بدون جمعیت هدف", NO_COVERAGE: "بدون پوشش" } as Record<string, string>)[s] || s || "-";
const statusClass = (s: string) => s === "CRITICAL" || s === "NO_COVERAGE" ? "danger" : s === "WARNING" ? "warning" : s === "ON_TRACK" ? "info" : "success";
const coverageStatus = (coverage: number) => coverage >= 90 ? "EXCELLENT" : coverage >= 75 ? "ON_TRACK" : coverage >= 50 ? "WARNING" : coverage > 0 ? "CRITICAL" : "NO_COVERAGE";
function matchesExecutive(label: string, v: Vaccine) { const type = normalize(v.vaccine_type), brand = normalize(v.vaccine_brand), disease = normalize(v.disease_name); if (label === "شاربن") return type.includes("شاربن") || disease.includes("شاربن"); if (label === "تب برفکی") return type.includes("تب برفکی") || disease.includes("تب برفکی"); if (label === "آبله") return type.includes("آبله") || disease.includes("آبله"); if (label === "لمپی‌اسکین") return type.includes("لمپی") || type.includes("لامپی") || disease.includes("لمپی") || disease.includes("لامپی"); if (label === "PPR") return type === "ppr" || type.includes("طاعون نشخوارکنندگان کوچک") || disease.includes("طاعون نشخوارکنندگان کوچک"); if (label === "FD REV1") return type.includes("rev1") || brand.includes("rev1") || brand.includes("ریو وان"); if (label === "بروسلوز میش") return type.includes("بروسلوز دام سبک") || (type.includes("بروسلوز") && v.animal_group === "LIGHT_LIVESTOCK"); if (label === "RD IRIBA") return (type.includes("iriba") || brand.includes("iriba")) && (type.includes("rd") || brand.includes("rd")); if (label === "FD IRIBA") return (type.includes("iriba") || brand.includes("iriba")) && (type.includes("fd") || brand.includes("fd")); if (label === "هاری") return type.includes("هاری") || disease.includes("هاری"); return false; }
function ChartTip({ active, payload, label }: any) { if (!active || !payload?.length) return null; return <div style={{ direction: "rtl", minWidth: 150, padding: "10px 12px", borderRadius: 12, background: "#061827", border: "1px solid #21637e", boxShadow: "0 14px 35px rgba(0,0,0,.35)" }}><div style={{ color: "#9be7f5", fontWeight: 900, marginBottom: 7 }}>{label}</div>{payload.map((p: any, i: number) => <div key={i} style={{ display: "flex", justifyContent: "space-between", gap: 16, color: "#dff8ff", fontSize: 11, marginTop: 4 }}><span>{p.name}</span><b>{typeof p.value === "number" && p.name?.includes("پوشش") ? pct(p.value) : fmt(p.value)}</b></div>)}</div>; }

export default function KPIAnalysis() {
  const navigate = useNavigate(); const [data, setData] = useState<Overview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [openCounty, setOpenCounty] = useState<string | number | null>(null);
  useEffect(() => { const controller = new AbortController(); fetch(`${API_BASE}/gis/kpi/vaccination/overview`, { headers: { Accept: "application/json", Authorization: `Bearer ${getToken()}` }, signal: controller.signal }).then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).then(setData).catch(e => { if (e?.name !== "AbortError") setError("خطا در دریافت داشبورد واکسیناسیون"); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, []);
  const executiveCards = useMemo(() => EXECUTIVE.map(label => { const rows = (data?.vaccines || []).filter(v => matchesExecutive(label, v)); if (!rows.length) return { label, data: null as Vaccine | null }; const target = rows.reduce((s, r) => s + Number(r.target_population || 0), 0); const vaccinated = rows.reduce((s, r) => s + Number(r.vaccinated_animals || 0), 0); const coverage = target ? vaccinated * 100 / target : 0; return { label, data: { ...rows[0], target_population: target, vaccinated_animals: vaccinated, remaining_animals: Math.max(target - vaccinated, 0), coverage_percent: coverage, progress_percent: coverage, status: coverageStatus(coverage) } as Vaccine }; }), [data]);
  const vaccineChart = useMemo(() => executiveCards.filter(x => x.data).map((x, i) => ({ name: x.label, coverage: Number(x.data?.coverage_percent || 0), color: COLORS[i % COLORS.length] })), [executiveCards]);
  const countyChart = useMemo(() => [...(data?.counties || [])].sort((a, b) => Number(b.coverage_percent || 0) - Number(a.coverage_percent || 0)).slice(0, 12).map(c => ({ ...c, label: c.county_name || "بدون نام", coverage: Number(c.coverage_percent || 0) })), [data]);
  const countyAlertChart = useMemo(() => [...(data?.booster_by_county || [])].sort((a, b) => Number(b.total_alerts || 0) - Number(a.total_alerts || 0)).slice(0, 10).map(c => ({ name: c.county_name || "بدون نام", overdue: Number(c.overdue || 0), dueSoon: Number(c.due_soon || 0) })), [data]);
  const coverageSplit = useMemo(() => [{ name: "واکسینه‌شده", value: Number(data?.summary.vaccinated_animals || 0) }, { name: "باقی‌مانده", value: Number(data?.summary.remaining_animals || 0) }].filter(x => x.value > 0), [data]);
  const surveillanceChart = useMemo(() => (data?.surveillance || []).map(s => ({ name: s.label, مثبت: Number(s.positive_count || 0), منفی: Number(s.negative_count || 0), مشکوک: Number(s.suspicious_count || 0) })).slice(0, 10), [data]);
  const selectedCounty = useMemo(() => data?.booster_by_county.find(c => String(c.county_code) === String(openCounty)) || null, [data, openCounty]);
  if (loading) return <div className="vaccination-overview" dir="rtl"><div className="section-block loading"><div className="loader" /><h2>در حال ساخت داشبورد مدیریتی…</h2><p>KPIها، عملکرد شهرستان‌ها، موجودی و هشدارهای عملیاتی در حال آماده‌سازی هستند.</p></div></div>;
  if (error || !data) return <div className="vaccination-overview" dir="rtl"><div className="section-block error"><h2>{error || "اطلاعاتی برای نمایش وجود ندارد"}</h2><button onClick={() => window.location.reload()}>تلاش مجدد</button></div></div>;
  return <div className="vaccination-overview" dir="rtl">
    <header className="overview-header"><div className="overview-title-wrap"><div className="eyebrow">GIS-VET · مرکز فرماندهی واکسیناسیون</div><h1>داشبورد مدیریتی KPI واکسیناسیون و کنترل بیماری‌های واگیر</h1><p>یک نمای عملیاتی برای دیدن پوشش واقعی، شکاف جمعیت هدف، رتبه شهرستان‌ها، هشدارهای ایمنی‌سازی، موجودی واکسن و وضعیت مراقبت.</p><div className="header-chips"><span>استان: {data.summary.province_names.join("، ") || "-"}</span><span>آخرین بروزرسانی: {dateFa(data.generated_at)}</span><span>آستانه هشدار: {data.booster_alert_days} روز</span></div></div><div className="hero-score"><span>پوشش کل معتبر</span><strong>{pct(data.summary.coverage_percent)}</strong><div className="hero-progress"><span style={{ width: `${Math.min(100, Math.max(0, Number(data.summary.coverage_percent || 0)))}%` }} /></div><small>{data.summary.coverage_is_valid ? "محاسبه بر پایه جمعیت هدف" : "پوشش کل قابل اتکا نیست"}</small></div></header>
    <section className="summary-grid"><div className="summary-card"><span>واحدهای درگیر</span><strong>{fmt(data.summary.units)}</strong><small>واحد اپیدمیولوژیک</small><b className="summary-icon">⌘</b></div><div className="summary-card"><span>شهرستان‌های درگیر</span><strong>{fmt(data.summary.counties)}</strong><small>{fmt(data.summary.vaccine_types)} نوع واکسن</small><b className="summary-icon">◈</b></div><div className="summary-card"><span>دام واکسینه‌شده</span><strong>{fmt(data.summary.vaccinated_animals)}</strong><small>از {fmt(data.summary.target_population)} جمعیت هدف</small><b className="summary-icon">✓</b></div><div className="summary-card alert-summary"><span>هشدارهای ایمنی‌سازی</span><strong>{fmt(data.booster_alerts.length)}</strong><small>{fmt(data.booster_alerts.filter(x => x.severity === "OVERDUE").length)} مورد سررسید گذشته</small><b className="summary-icon">!</b></div></section>
    <section className="section-block executive-block"><div className="section-head"><div><h2>شاخص‌های اجرایی واکسیناسیون</h2><p>کارت‌ها بر اساس جمعیت هدف تجمیع شده‌اند؛ انتخاب هر کارت وارد گزارش تحلیلی همان واکسن می‌شود.</p></div><span className="section-kicker">{vaccineChart.length} برنامه دارای داده</span></div><div className="vaccine-grid">{executiveCards.map(({ label, data: v }, index) => <button key={label} className={`vaccine-card ${v ? "has-data" : "no-data"}`} onClick={() => v && navigate(`/gis/kpi/vaccination/vaccine/${encodeURIComponent(v.vaccine_type || label)}?animal_group=${encodeURIComponent(v.animal_group || "")}`)}><div className="vaccine-accent" style={{ background: COLORS[index % COLORS.length] }} /><div className="vaccine-top"><span className="vaccine-name">{label}</span>{v && <span className={`status-badge ${statusClass(v.status)}`}>{statusText(v.status)}</span>}</div>{v ? <><div className="vaccine-coverage">{pct(v.coverage_percent)}</div><div className="progress-track"><span style={{ width: `${Math.min(100, Math.max(0, Number(v.coverage_percent || 0)))}%`, background: COLORS[index % COLORS.length] }} /></div><div className="vaccine-stats"><span>هدف<b>{fmt(v.target_population)}</b></span><span>واکسینه<b>{fmt(v.vaccinated_animals)}</b></span><span>باقی‌مانده<b>{fmt(v.remaining_animals)}</b></span></div><div className="vaccine-meta">{v.animal_group_name || "گروه دام نامشخص"} · {v.vaccine_brand || "برند نامشخص"}</div></> : <div className="missing">برای این برنامه داده نرمال‌شده‌ای پیدا نشد.</div>}</button>)}</div></section>
    <section className="dashboard-charts"><div className="section-block chart-card-large"><div className="section-head"><div><h2>مقایسه پوشش برنامه‌ها</h2><p>خط ۹۰٪ آستانه هدف مدیریتی است؛ ستون‌ها بر اساس پوشش واقعی مرتب شده‌اند.</p></div><span className="chart-badge">تحلیل مقایسه‌ای</span></div><div className="chart-wrap tall"><ResponsiveContainer width="100%" height="100%"><BarChart data={vaccineChart} layout="vertical" margin={{ top: 8, right: 18, left: 16, bottom: 6 }} barCategoryGap="24%"><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" domain={[0, 100]} tickFormatter={(x) => `${x}%`} /><YAxis type="category" dataKey="name" width={95} tickLine={false} axisLine={false} /><Tooltip content={<ChartTip />} /><ReferenceLine x={90} stroke="#34d399" strokeDasharray="5 5" /><Bar dataKey="coverage" name="پوشش" radius={[0, 8, 8, 0]}>{vaccineChart.map((x, i) => <Cell key={i} fill={x.color} />)}</Bar></BarChart></ResponsiveContainer></div></div><div className="section-block"><div className="section-head"><div><h2>ترکیب جمعیت</h2><p>این نمودار فقط وقتی معتبر است که جمعیت هدف قابل اتکا باشد.</p></div><span className="chart-badge">{data.summary.coverage_is_valid ? "معتبر" : "هشدار"}</span></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={coverageSplit} dataKey="value" nameKey="name" innerRadius="66%" outerRadius="86%" paddingAngle={3} stroke="none"><Cell fill="#22d3ee" /><Cell fill="#294559" /></Pie><Tooltip content={<ChartTip />} /></PieChart></ResponsiveContainer><div className="donut-center"><strong>{pct(data.summary.coverage_percent)}</strong><span>پوشش کل</span></div></div><div className="mini-metrics"><div><b>{fmt(data.summary.vaccinated_animals)}</b><span>واکسینه‌شده</span></div><div><b>{fmt(data.summary.remaining_animals)}</b><span>باقی‌مانده</span></div></div></div></section>
    <section className="section-block"><div className="section-head"><div><h2>رتبه عملکرد شهرستان‌ها</h2><p>۱۲ شهرستان برتر برای خوانایی نمودار؛ جدول پایین‌تر کل شهرستان‌های API را در اختیار دارد.</p></div><span className="chart-badge">Drill-down</span></div><div className="chart-wrap county-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={countyChart} layout="vertical" margin={{ top: 6, right: 18, left: 18, bottom: 4 }} barCategoryGap="20%"><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" domain={[0, 100]} tickFormatter={(x) => `${x}%`} /><YAxis type="category" dataKey="label" width={110} tickLine={false} axisLine={false} /><Tooltip content={<ChartTip />} /><ReferenceLine x={90} stroke="#34d399" strokeDasharray="5 5" /><Bar dataKey="coverage" name="پوشش" fill="#38bdf8" radius={[0, 7, 7, 0]} onClick={(entry: any) => entry?.payload?.county_code != null && setOpenCounty(entry.payload.county_code)} /></BarChart></ResponsiveContainer></div>{selectedCounty && <div className="selected-note">شهرستان انتخاب‌شده برای Drill-down: <b>{selectedCounty.county_name}</b> · {fmt(selectedCounty.total_alerts)} هشدار</div>}</section>
    <section className="section-block"><div className="section-head"><div><h2>فشار هشدارهای ایمنی‌سازی به تفکیک شهرستان</h2><p>قرمز = سررسید گذشته، زرد = نزدیک به سررسید. شهرستان‌های پرریسک در ابتدای نمودار دیده می‌شوند.</p></div><span className="chart-badge">عملیاتی</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={countyAlertChart} layout="vertical" margin={{ top: 6, right: 18, left: 18, bottom: 4 }} barCategoryGap="18%"><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" /><YAxis type="category" dataKey="name" width={110} tickLine={false} axisLine={false} /><Tooltip content={<ChartTip />} /><Legend /><Bar dataKey="overdue" name="سررسید گذشته" stackId="alerts" fill="#fb7185" radius={[0, 5, 5, 0]} /><Bar dataKey="dueSoon" name="نزدیک به سررسید" stackId="alerts" fill="#fbbf24" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div></section>
    <section className="dashboard-bottom-grid"><div className="section-block"><div className="section-head"><div><h2>وضعیت مراقبت و نمونه‌ها</h2><p>مثبت، منفی و مشکوک برای سریع‌ترین تشخیص نقاط فشار مراقبتی.</p></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={surveillanceChart} margin={{ top: 10, right: 8, left: 0, bottom: 0 }}><defs><linearGradient id="posFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#fb7185" stopOpacity={0.42}/><stop offset="100%" stopColor="#fb7185" stopOpacity={0.02}/></linearGradient><linearGradient id="negFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22d3ee" stopOpacity={0.35}/><stop offset="100%" stopColor="#22d3ee" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} /><Tooltip content={<ChartTip />} /><Legend /><Area type="monotone" dataKey="مثبت" stroke="#fb7185" fill="url(#posFill)" strokeWidth={2.5}/><Area type="monotone" dataKey="منفی" stroke="#22d3ee" fill="url(#negFill)" strokeWidth={2.5}/><Area type="monotone" dataKey="مشکوک" stroke="#fbbf24" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="section-block"><div className="section-head"><div><h2>موجودی واکسن</h2><p>تمرکز روی موجودی قابل استفاده و اقلام نزدیک به انقضا.</p></div><span className="chart-badge">{data.inventory_summary.near_expiry_days} روز</span></div><div className="inventory-summary"><div><b>{fmt(data.inventory_summary.total_lots)}</b><span>لات</span></div><div><b>{fmt(data.inventory_summary.total_packages)}</b><span>بسته</span></div><div className="expiry"><b>{fmt(data.inventory_summary.near_expiry_lots)}</b><span>نزدیک انقضا</span></div></div><div className="expiry-list">{data.inventory_summary.near_expiry.slice(0, 7).map((item, i) => <div className="expiry-row" key={`${item.batch_number}-${i}`}><div><b>{item.vaccine_type || item.vaccine_brand || "واکسن"}</b><small>{item.unit_name || item.county_name || "-"} · سری {item.batch_number || "-"}</small></div><strong>{item.days_to_expiry == null ? "-" : `${fmt(item.days_to_expiry)} روز`}</strong></div>)}{!data.inventory_summary.near_expiry.length && <div className="empty-state">مورد نزدیک به انقضا ثبت نشده است.</div>}</div></div></section>
    <section className="section-block"><div className="section-head"><div><h2>جدول عملکرد شهرستان‌ها</h2><p>انتخاب شهرستان، Drill-down هشدارهای ایمنی‌سازی همان منطقه را فعال می‌کند.</p></div><span className="section-kicker">{data.counties.length} شهرستان</span></div><div className="county-table-wrap"><table><thead><tr><th>شهرستان</th><th>واحد</th><th>هدف</th><th>واکسینه</th><th>باقی‌مانده</th><th>پوشش</th><th>وضعیت</th></tr></thead><tbody>{data.counties.map(c => <tr key={String(c.county_code)} className={String(c.county_code) === String(openCounty) ? "active-row" : ""} onClick={() => setOpenCounty(c.county_code)}><td><b>{c.county_name || "بدون نام"}</b></td><td>{fmt(c.units)}</td><td>{fmt(c.target_population)}</td><td>{fmt(c.vaccinated_animals)}</td><td>{fmt(c.remaining_animals)}</td><td><strong className={statusClass(c.status)}>{pct(c.coverage_percent)}</strong></td><td><span className={`status-badge ${statusClass(c.status)}`}>{statusText(c.status)}</span></td></tr>)}</tbody></table></div></section>
    {selectedCounty && <section className="section-block county-alert-detail"><div className="section-head"><div><h2>هشدارهای شهرستان {selectedCounty.county_name}</h2><p>{fmt(selectedCounty.overdue)} سررسید گذشته · {fmt(selectedCounty.due_soon)} نزدیک به سررسید</p></div><button className="ghost-button" onClick={() => setOpenCounty(null)}>بستن Drill-down</button></div><div className="alert-grid">{selectedCounty.units.slice(0, 12).map((a, i) => <button key={`${a.unit_code}-${a.vaccine_type}-${i}`} className={`alert-row ${a.severity === "OVERDUE" ? "overdue" : "due-soon"}`} onClick={() => navigate(`/gis/kpi/vaccination/vaccine/${encodeURIComponent(a.vaccine_type || "واکسن")}`)}><span><b>{a.unit_name || a.unit_code || "واحد"}</b><small>{a.vaccine_type || "واکسن"} · {a.animal_group_name || "گروه دام"}</small></span><strong>{a.severity === "OVERDUE" ? "گذشته" : `${fmt(Math.max(a.days_until_due, 0))} روز`}</strong></button>)}</div></section>}
    <section className="section-block"><div className="section-head"><div><h2>قواعد محاسبه ایمنی‌سازی</h2><p>مقادیر محاسباتی برای تفسیر داشبورد در یک نگاه.</p></div></div><div className="rule-grid"><div><span>تب برفکی</span><b>{fmt(data.fmd_immunity_days)} روز</b></div><div><span>سایر واکسن‌ها</span><b>{fmt(data.default_immunity_days)} روز</b></div><div><span>آستانه هشدار</span><b>{fmt(data.booster_alert_days)} روز</b></div></div></section>
  </div>;
}
